package nl.whitedove.washetdroogofniet;

import java.util.ArrayList;
import java.util.Random;


class SpreukenHelper {

    private static final ArrayList<Spreuk>[] mLijst = new ArrayList[12];
    private static final ArrayList<Spreuk>[] dLijst = new ArrayList[12];
    private static final Random rnd = new Random();

    private static void nieuweSpreuk(int maand, int dag, String sSpreuk) {
        Spreuk spreuk = new Spreuk(maand, dag, sSpreuk);
        if (dag == 0) {
            mLijst[maand - 1].add(spreuk);
        } else {
            dLijst[maand - 1].add(spreuk);
        }
    }

    static String GeefSpreuk(int maand, int dag) {
        MaakLijst();

        ArrayList<Spreuk> daglijst = dLijst[maand - 1];
        ArrayList<Spreuk> vandaaglijst = new ArrayList<>();

        for (Spreuk spreuk : daglijst) {
            if (spreuk.getDag() == dag) {
                vandaaglijst.add(spreuk);
            }
        }

        if (vandaaglijst.size()>0)
        {
            int index = rnd.nextInt(vandaaglijst.size());
            return vandaaglijst.get(index).getSpreuk();
        }

        ArrayList<Spreuk> maandlijst = mLijst[maand - 1];
        int index = rnd.nextInt(maandlijst.size());
        return maandlijst.get(index).getSpreuk();
    }

    private static void MaakLijst() {

        if (mLijst[0] != null) {
            return;
        }

        mLijst[0] = new ArrayList<>();
        mLijst[1] = new ArrayList<>();
        mLijst[2] = new ArrayList<>();
        mLijst[3] = new ArrayList<>();
        mLijst[4] = new ArrayList<>();
        mLijst[5] = new ArrayList<>();
        mLijst[6] = new ArrayList<>();
        mLijst[7] = new ArrayList<>();
        mLijst[8] = new ArrayList<>();
        mLijst[9] = new ArrayList<>();
        mLijst[10] = new ArrayList<>();
        mLijst[11] = new ArrayList<>();

        dLijst[0] = new ArrayList<>();
        dLijst[1] = new ArrayList<>();
        dLijst[2] = new ArrayList<>();
        dLijst[3] = new ArrayList<>();
        dLijst[4] = new ArrayList<>();
        dLijst[5] = new ArrayList<>();
        dLijst[6] = new ArrayList<>();
        dLijst[7] = new ArrayList<>();
        dLijst[8] = new ArrayList<>();
        dLijst[9] = new ArrayList<>();
        dLijst[10] = new ArrayList<>();
        dLijst[11] = new ArrayList<>();

        nieuweSpreuk(1, 29, "Als de schaatsliefhebbers op St. Sulpitus (29-1) op de schaats staan,zal het weer in het voorjaar van slag zijn.");
        nieuweSpreuk(1, 25, "Is het op St. Paulus (25-1) schoon en klaar, dan brengt het een gezegend korenjaar.");
        nieuweSpreuk(1, 20, "Als het vriest op St. Sebastiaan (20-1), dan is het op 2 februari met de vorst gedaan.");
        nieuweSpreuk(1, 17, "Als het vriest met St. Antonius (17-1), dan dooit het op St. Sebastiaan(20-1).");
        nieuweSpreuk(1, 13, "Geeft St. Hilarius (13-1) zonneschijn, weldra zal het kouder zijn.");
        nieuweSpreuk(1, 6, "Als het vriest op Driekoningendag (6-1), dan vries het dertien weken lang.");
        nieuweSpreuk(1, 0, "Als de dagen lengen, begint de winter te strengen.");
        nieuweSpreuk(1, 0, "Als de kat in januari in de zon ligt, ligt ze in februari achter de kachel.");
        nieuweSpreuk(1, 0, "Als het in januari mistig is, dan wordt de lente fris.");
        nieuweSpreuk(1, 0, "Als in januari de muggen zwermen, dan kun je in maart de oren wermen.");
        nieuweSpreuk(1, 0, "Als in januari de vorst niet komen wil, dan is zij er zeker in april.");
        nieuweSpreuk(1, 0, "Draagt januari een sneeuwwit kleed, wordt de zomer zeer heet.");
        nieuweSpreuk(1, 0, "Geeft januari een sneeuwtapijt dan zijn we de winter nog zeker niet kwijt.");
        nieuweSpreuk(1, 0, "Gelijk Januari, zo ook juli.");
        nieuweSpreuk(1, 0, "Heeft januari koude en droge dagen, dan zal in februari de sneeuw u plagen.");
        nieuweSpreuk(1, 0, "Is in januari van sneeuwvlagen arm dan volgt vaak een zomer schoon en arm.");
        nieuweSpreuk(1, 0, "Januari zonder regen is de boerenstand een zegen.");
        nieuweSpreuk(1, 0, "Januari zonder regen, is voor de boerenstand een zegen.");
        nieuweSpreuk(1, 0, "Nevels in januari opgestaan, brengt een natte lente aan.");
        nieuweSpreuk(1, 0, "Op een milde januari, volgt vaak een gure lente, en een warme zomer.");
        nieuweSpreuk(2, 24, "St. Matthijs (24-2) breekt het ijs, maar wil het ijs niet breken, dan vriest het nog zes weken.");
        nieuweSpreuk(2, 17, "Klaar weer op St. Silvijn (17-2), het kan nog twee maanden winter zijn.");
        nieuweSpreuk(2, 7, "Op Romaldus (7-2) storm en blazen, zal in mei het vee doen grazen.");
        nieuweSpreuk(2, 2, "Brengt Lichtmis (2-2) wolken en regen mee, dan is de winter voorbij en komt niet meer.");
        nieuweSpreuk(2, 2, "Lichtmis (2-2) donker maakt de boer tot jonker.");
        nieuweSpreuk(2, 2, "Geeft Lichtmis (2-2) klaverblad, met Pasen sneeuw op het pad.");
        nieuweSpreuk(2, 2, "Lichtmis (2-2) helder en klaar, maakt de boer tot bedelaar.");
        nieuweSpreuk(2, 0, "Als februari lacht, dan wordt maart niet zacht.");
        nieuweSpreuk(2, 0, "Als het in februari niet sneeuwt, weet dan dat je later, in de zomer van hitte geeuwt.");
        nieuweSpreuk(2, 0, "Als in februari de muggen zwermen, moet ge in maart uw oren wermen (warmen).");
        nieuweSpreuk(2, 0, "Als vroeg krokussen bloeien, dan zullen ze met de koude stoeien.");
        nieuweSpreuk(2, 0, "Een koude februari geeft een goed roggejaar.");
        nieuweSpreuk(2, 0, "Februari is nooit zo fel, of ze geeft drie lentedagen wel.");
        nieuweSpreuk(2, 0, "Februari komt verklaren, dat men hout en kool moet sparen.");
        nieuweSpreuk(2, 0, "Februari met vorst en wind, maakt weldra de pasen blind.");
        nieuweSpreuk(2, 0, "Februari muggendans, geeft voor maart een slechte kans.");
        nieuweSpreuk(2, 0, "Geeft de sprokkelmaand de winter niet, dan ligt ze voor Pasen in het verschiet.");
        nieuweSpreuk(2, 0, "Groeit in februari al het gras, dan lopen we met Pasen in een dikke jas.");
        nieuweSpreuk(2, 0, "In de korte maand regen, is vette mest en zegen");
        nieuweSpreuk(2, 0, "In februari al de lente? Dat geeft broden zonder krenten.");
        nieuweSpreuk(2, 0, "In februari een muggendans, Geeft voor mrt een slechte kant");
        nieuweSpreuk(2, 0, "In februari guur en koud, dan komt er een zomer waarvan je houdt");
        nieuweSpreuk(2, 0, "In februari ziet de boer liever een hongerige wolf, dan een man in hemdsmouwen.");
        nieuweSpreuk(2, 0, "Is februari nat en koel, dan wordt juli dikwijls heet en zwoel.");
        nieuweSpreuk(2, 0, "Komt Februari met goed weer, dan vriest ’t in voorjaar des te meer.");
        nieuweSpreuk(2, 0, "Het weer op de 29e, is het weer van de 5e februari.");
        nieuweSpreuk(2, 0, "Komt februari met veel zacht weer, dan vriest het straks in het voorjaar des te meer.");
        nieuweSpreuk(2, 0, "Nooit is de schrikkelmaand zo fel of ze heeft haar 5 schone dagen wel.");
        nieuweSpreuk(2, 0, "Is februari guur en koud, volgt vaak een zomer waar men van houdt.");
        nieuweSpreuk(2, 0, "Schijnt morgen rood je tegen, dan dreigt februari met regen");
        nieuweSpreuk(2, 0, "Sprokkelmaands regen, is grasmaands zegen.");
        nieuweSpreuk(2, 0, "Vliegt de mug in februari, dan huivert men het ganse jaar");
        nieuweSpreuk(2, 0, "Wanneer februari iedereen winst brengt, dan klagen de boeren het minst.");
        nieuweSpreuk(2, 0, "Zingt de leeuwerik hoog in de lucht, heerlijk weer voorspelt zijn vlucht.");
        nieuweSpreuk(3, 27, "Is het op St. Rupertus (27-3) helder en rein, zo zal ook de zomer zijn.");
        nieuweSpreuk(3, 21, "Op de Lentedag (21-3) de wind in noord, dan blaast deze nog zeven weken voort.");
        nieuweSpreuk(3, 19, "Sint Jozef (19-3) schoon en goed, (mooie dag) een vuchtbaar jaar ligt in’t verschiet.");
        nieuweSpreuk(3, 12, "Zo de wind staat op St. Gregorius (12-3), zo staat hij nog veertig dagen.");
        nieuweSpreuk(3, 1, "Regent het met St. Albinus (1-3) dat het giet, dan doet de boer dat veel verdriet.");
        nieuweSpreuk(3, 0, "Als het helder is op St. Jozefdag, een goed jaar men verwachten mag");
        nieuweSpreuk(3, 0, "Als het weder is van goede zin, trekt de kou zijn steertje in");
        nieuweSpreuk(3, 0, "Als hij komt en als hij scheidt, heeft d’oude Maart zijn gift bereid.");
        nieuweSpreuk(3, 0, "Als maart geeft april weer, geeft april maarts weer. ");
        nieuweSpreuk(3, 0, "Autoruiten nu nog steeds bevroren, dat geeft straks veel koren.");
        nieuweSpreuk(3, 0, "Brengt maart storm en wind, de sikkel is de boer gezind.");
        nieuweSpreuk(3, 0, "Daar is geen maart zo goed, of het sneeuw wel op de boer zijn hoed.");
        nieuweSpreuk(3, 0, "Danst het lammetje in maart, april pakt het bij de staart.");
        nieuweSpreuk(3, 0, "Donder in maart, vorst in april.");
        nieuweSpreuk(3, 0, "Een droge maart en een natte april, dat is de boeren naar zijn wil.");
        nieuweSpreuk(3, 0, "Een droge maart en een natte april, dat is de boeren naar zijn wil. ");
        nieuweSpreuk(3, 0, "Een droge maart, een natte april, een koele mei, vullen de schuren en de kelders van de boer.");
        nieuweSpreuk(3, 0, "Een droge maart, is een zomer te paard.");
        nieuweSpreuk(3, 0, "Een droge maartse wind, maakt de boeren goed gezind.");
        nieuweSpreuk(3, 0, "Een koekoe’sroep ter helft van maart, is voor de boer een daalder waard.");
        nieuweSpreuk(3, 0, "Een koekoeksroep ter helft van maart, is voor de boer een daalder waard.");
        nieuweSpreuk(3, 0, "Een natte maart, geeft veel lijnzaad.");
        nieuweSpreuk(3, 0, "Geeft maart al veel gedonder, dan is een witte Paas geen wonder.");
        nieuweSpreuk(3, 0, "Komt men in maart omweer tegen, dan krijgt men in juli regen.");
        nieuweSpreuk(3, 0, "Koude in maart, dan een lente te paard.");
        nieuweSpreuk(3, 0, "Lentemaands ruwheid geeft zomermaands luwheid.");
        nieuweSpreuk(3, 0, "Maart guur geeft een volle schuur.");
        nieuweSpreuk(3, 0, "Maart niet te droog en niet te nat, Vult de boer zijn kist en vat.");
        nieuweSpreuk(3, 0, "Maart roert zijn staart, april doet wat hij wil en mei doet er ook nog wat bij.");
        nieuweSpreuk(3, 0, "Maartse buien die beduien, dat de zomer aan komt kruien.");
        nieuweSpreuk(3, 0, "Maartse maan, brengt kwaad weer.");
        nieuweSpreuk(3, 0, "Maartse regen, brengt geen zegen.");
        nieuweSpreuk(3, 0, "Maartse zon en aprilse wind, schenden menig lieflijk kind.");
        nieuweSpreuk(3, 0, "Mist in maart, water en vorst in mei.");
        nieuweSpreuk(3, 0, "Niet te droog, niet te nat, dan vult maart een duchtig vat.");
        nieuweSpreuk(3, 0, "Regen voor 8 uur is nooit van lange duur.");
        nieuweSpreuk(3, 0, "Sneeuw en hagel, regen en wind – daarvan is maart een vrind.");
        nieuweSpreuk(3, 0, "Stof in maart, is goud waard.");
        nieuweSpreuk(3, 0, "Voor oude lieden heeft maart, kwaad in haar staart.");
        nieuweSpreuk(3, 0, "Waait de wind in maart te fel, veel fruit verwacht men wel.");
        nieuweSpreuk(3, 0, "Wat maart niet wil, dat neemt april.");
        nieuweSpreuk(3, 0, "Zoveel nevel in maart, zoveel onweer s’ zomers.");
        nieuweSpreuk(4, 28, "Als het vriest op St. Vitaal (28-4), vriest het nog veertig maal.");
        nieuweSpreuk(4, 25, "Zolang voor Sint Markus (25-4) warm, zolang na hem koud.");
        nieuweSpreuk(4, 23, "Valt voor Sint Joris (23-4) geen regen, dan komt erna hem des te meer.");
        nieuweSpreuk(4, 15, "Op Sint Justijn (15-4), dood de kou het venijn.");
        nieuweSpreuk(4, 14, "Op Sint Tuburtius (14-4) na de noen (3uur in de middag), worden alle velden groen.");
        nieuweSpreuk(4, 10, "Zaait ge op Sint Ezechiel (10-4), zeker lukt de vlasgaard wel.");
        nieuweSpreuk(4, 3, "Is Isodoor (3-4) voorbij, dan is ook de noordenwind voorbij.");
        nieuweSpreuk(4, 0, "Al doet april ons mooi weer aanschouwen, ’t is evenals fortuin, we kunnen hem niet vertrouwen.");
        nieuweSpreuk(4, 0, "Als april lacht, boerke wees voor uw oogst bedacht.");
        nieuweSpreuk(4, 0, "Als de hoenders kakelen lang en goed, zal het regenen in overvloedt.");
        nieuweSpreuk(4, 0, "Als het in april regenen wil, blijven de boeren niet stil.");
        nieuweSpreuk(4, 0, "Als in april kevers ontstaan, dan zal de mei van kou vergaan.");
        nieuweSpreuk(4, 0, "April doet wat hij wil.");
        nieuweSpreuk(4, 0, "April maakt de bloem, en mei bekomt de roem.");
        nieuweSpreuk(4, 0, "April mooi en rein, in mei zal het donker zijn.");
        nieuweSpreuk(4, 0, "April veel regen, brengt grote zegen.");
        nieuweSpreuk(4, 0, "April verandelijk en guur, brengt hooi en koren in de schuur.");
        nieuweSpreuk(4, 0, "April vult vele zolders, dankzij de vele donders.");
        nieuweSpreuk(4, 0, "April warm, Mei koel en Juni nat, vullen schuur en ook het vat.");
        nieuweSpreuk(4, 0, "Aprilleke zoet, geeft nog weleens een witte hoed.");
        nieuweSpreuk(4, 0, "Aprillertje zoet, geeft nog wel eens een witte hoed.");
        nieuweSpreuk(4, 0, "Aprillezonne, doet water in de tonne.");
        nieuweSpreuk(4, 0, "Aprilse aren, zijn er alle jaren.");
        nieuweSpreuk(4, 0, "Aprilse vlokjes, brengen mei’se klokjes.");
        nieuweSpreuk(4, 0, "Aprilvlokjes brengen meiklokjes");
        nieuweSpreuk(4, 0, "Bloeien de bomen tweemaal op een rij, zal de winter zich rekken tot mei.");
        nieuweSpreuk(4, 0, "Broedt de spreeuw al in april, dan is een schone meimaand op til.");
        nieuweSpreuk(4, 0, "De heren en aprillen, bedriegen wie ze willen.");
        nieuweSpreuk(4, 0, "De huwelijkse staat, is als april, nu zon, dan storm, en dan weer alles stil.");
        nieuweSpreuk(4, 0, "De vrouwen en aprillen, ze hebben beide hun grillen.");
        nieuweSpreuk(4, 0, "Een grote zon en bleek van schijn, dan zal het regenachtig zijn.");
        nieuweSpreuk(4, 0, "Een natte april ,is de boeren naar hun wil.");
        nieuweSpreuk(4, 0, "Geen zaterdag zo kwaad, of de zon schijn vroeg of laat.");
        nieuweSpreuk(4, 0, "Gras dat in april wast, staat in mei vast. ");
        nieuweSpreuk(4, 0, "Grasmaands gril is hooimaands wil.");
        nieuweSpreuk(4, 0, "Hebben wolken rode randen, altijd is er wind en nats voorhanden.");
        nieuweSpreuk(4, 0, "Heldere maneschijn in de aprilnacht, schaadt allicht veel bloesempracht.");
        nieuweSpreuk(4, 0, "Het groen des velds het oog bekoort doch zelden houdt april haar woord.");
        nieuweSpreuk(4, 0, "Het zaterdagse weer op noen, is op de zondag heel te dag te doen.");
        nieuweSpreuk(4, 0, "Hoe groen het in het veld ook ons oog bekoort, doch zelden houdt april zijn woord.");
        nieuweSpreuk(4, 0, "In april heldere maaneschijn, zal voor de bloesem kwalijk zijn.");
        nieuweSpreuk(4, 0, "Is april schoon en rein, dan zal mei minder zijn.");
        nieuweSpreuk(4, 0, "Is het in april nat en koud, dan groeit straks het koren als een woud.");
        nieuweSpreuk(4, 0, "Laat het weer zoals het wil, maar ontkleedt u niet voor half april.");
        nieuweSpreuk(4, 0, "Mocht het dauwen in april en mei, dan is de boer in sept blij.");
        nieuweSpreuk(4, 0, "Nachtvorst met een Zuidenwind op kersenbloem, daar treurt de kweker om.");
        nieuweSpreuk(4, 0, "Op een april geen zon, vaak water in de ton.");
        nieuweSpreuk(4, 0, "Op een droge april volgt wel eens een droge zomer.");
        nieuweSpreuk(4, 0, "Sneeuw in april geen nood, met zware nachtvorst veel meer dood.");
        nieuweSpreuk(4, 0, "Sneeuw in april is geen nood, maar bij zware nachtvorst in april gaat er meer dood.");
        nieuweSpreuk(4, 0, "Sneeuwt april nog op onze hoed, het is voor de druiven en het koren goed.");
        nieuweSpreuk(4, 0, "Valt in april veel nat, dan zwemmen de druiven tot in het vat.");
        nieuweSpreuk(4, 0, "Valt voor St. Joris geen regen meer, dan valt er na hem des te meer.");
        nieuweSpreuk(4, 0, "Verschaft april veel schone dagen, dan pleegt mei de last te dragen.");
        nieuweSpreuk(4, 0, "Verschaft april vele schone dagen, dan pleegt mei de last te dragen.");
        nieuweSpreuk(5, 31, "Is het klaar met Petronel (31-5), dan meet men vlas met een el.");
        nieuweSpreuk(5, 25, "Sint Urbanus (25-5) en de zon,wijn in de ton.");
        nieuweSpreuk(5, 13, "Wie zijn schaap scheert voor St. Servaas (13-5) houdt meer van wol dan van het schaap.");
        nieuweSpreuk(5, 1, "Als het op Sint Filippus (1-5) regent, is de oost gezegend.");
        nieuweSpreuk(5, 0, "Als de bij naar huis toe vlucht, zit er regen in de lucht.");
        nieuweSpreuk(5, 0, "Als de eikels in mei gaan bloeien, zal alles volop gaan groeien.");
        nieuweSpreuk(5, 0, "Als het dondert in mei, valt er dikwijls regen bij.");
        nieuweSpreuk(5, 0, "Als het onweert in mei, valt er vaak hagel bij.");
        nieuweSpreuk(5, 0, "Als is Marmertus oud en grijs, houdt hij van vriezen en van ijs.");
        nieuweSpreuk(5, 0, "Avonddauw en zon in mei, is hooi met karren op de wei.");
        nieuweSpreuk(5, 0, "Broedt de spreeuw vroeg in april, er is een schone mei op til.");
        nieuweSpreuk(5, 0, "De zonne in de meie, zet oude lieden aan het vrijen.");
        nieuweSpreuk(5, 0, "Een bijenzwerm in mei,is een goed teken voor de wei.");
        nieuweSpreuk(5, 0, "Een koude maand mei, een goude mei.");
        nieuweSpreuk(5, 0, "Een natte mei geeft boter in de wei.");
        nieuweSpreuk(5, 0, "Heden schupjes, morgen drupjes.");
        nieuweSpreuk(5, 0, "Het onweer in de schone mei, doet het koren bloeien op de hei.");
        nieuweSpreuk(5, 0, "Hoe meer onweer in mei, zoveel minder in de herfst..");
        nieuweSpreuk(5, 0, "IJsheilige hebben koude koppen.");
        nieuweSpreuk(5, 0, "In mei een warme regen, betekent vruchtenzegen");
        nieuweSpreuk(5, 0, "In mei nat, een droge juni volgt haar pad.");
        nieuweSpreuk(5, 0, "In mei staat het vast, zijn vaak de en de hoed tot last.");
        nieuweSpreuk(5, 0, "Is ’t koud en bloeit de Meidoorn, veel van haar pracht gaat verloren.");
        nieuweSpreuk(5, 0, "Is het weer in mei te mooi dan ziet de schuur maar weinig hooi.");
        nieuweSpreuk(5, 0, "Is mei nat, een droge juni volgt zijn pad.");
        nieuweSpreuk(5, 0, "Kamillegeur in mei, brengt de zomer dichterbij.");
        nieuweSpreuk(5, 0, "Kan vriezen in mei tot de ijsheilige voorbij zijn.");
        nieuweSpreuk(5, 0, "Krimpende wind, Stinkende wind.");
        nieuweSpreuk(5, 0, "Mei koel en te nat, brengt koren in het vat.");
        nieuweSpreuk(5, 0, "Mei nat, spek in het vat.");
        nieuweSpreuk(5, 0, "Mei niet te koud en niet te nat, vult de schuur en ook het vat.");
        nieuweSpreuk(5, 0, "Mei tot jubelmaand verkoren, heeft toch rijm achter de oren.");
        nieuweSpreuk(5, 0, "Meiregen op het zaad, is goud op de plaat.");
        nieuweSpreuk(5, 0, "Nachtvorst in mei, houdt jonge groen niet schadevrij.");
        nieuweSpreuk(5, 0, "Onweer in mei, gras in de wei.");
        nieuweSpreuk(5, 0, "Onweer in mei, maakt de boeren blij.Meikeverjaar goed jaar.");
        nieuweSpreuk(5, 0, "Pancras, Servaas en Bonifaas, ze geven vorst en ijs helaas.");
        nieuweSpreuk(5, 0, "Regen en wind in het midden van mei, maakt de boeren vast niet blij.");
        nieuweSpreuk(5, 0, "Roept de houtduif keer op keer, dan komt er vast en zeker mooi weer.");
        nieuweSpreuk(5, 0, "Scheert de zwaluw over water en wegen, dan komt of blijft er wind en regen.");
        nieuweSpreuk(5, 0, "Voor ijsheilige de bloemen buiten, veelal kan je daar naar fluiten, wacht of tot ze zijn voorbij, de bloemen zijn dan blij.");
        nieuweSpreuk(5, 0, "Voor nachtvorst bent u niet beschermd tot St. Servaas zich over u ontfermt.");
        nieuweSpreuk(5, 0, "Weest op uw hoede, en wacht nu wel, mei baart dikwijls kattenspel.");
        nieuweSpreuk(5, 0, "Wie nu zijn koren zaait, voelt zich later niet bekaaid.");
        nieuweSpreuk(5, 0, "Zingt de vink vroeg in de meimorgen, dan zal die dag voor regen zorgen.");
        nieuweSpreuk(5, 0, "Zoele mei, boerengeschrei.");
        nieuweSpreuk(6, 29, "Als op St. Pieter (29-6) het haantje kraait, komt het regenweer ons toegewaaid.");
        nieuweSpreuk(6, 24, "Het weer van St. Jan (24-6), houdt dertig dagen aan.");
        nieuweSpreuk(6, 15, "Regen met Sint Veith (15-6), dan regen het zes weken in de tijd.");
        nieuweSpreuk(6, 13, "Is het op Sint Antonius (13-6) nat, de boer drinkt zich van verdriet zat.");
        nieuweSpreuk(6, 11, "Regen op Sint Barnabas (11-6), dan zwemt de oogst in de waterplas.");
        nieuweSpreuk(6, 10, "Heeft Magriet (10-6) geen zonneschijn, dan zal het een natte zomer zijn.");
        nieuweSpreuk(6, 1, "Wat St. Medardus (1-6), geeft droog of nat, zes weken duurt het dit of dat.");
        nieuweSpreuk(6, 0, "Als de noordenwind in juni staat, komt het onweer veel te laat.");
        nieuweSpreuk(6, 0, "Als het koud en nat in juni is, dan is het heel het jaar ook mis.");
        nieuweSpreuk(6, 0, "Blaast de wind in juni uit de noorderkant, zo waait het koren van het land.");
        nieuweSpreuk(6, 0, "Blaast juni uit de noorderkant, verwacht veel koren op het land.");
        nieuweSpreuk(6, 0, "Boeren maaien nu hun grasjes, stedelingen pakken hun terrasjes.");
        nieuweSpreuk(6, 0, "Donderweer in juni maakt het koren dik.");
        nieuweSpreuk(6, 0, "Een boon in juni geplant, geeft er vijftig in de hand.");
        nieuweSpreuk(6, 0, "Een wei die in juni niets geeft, is niet waard dat ze leeft.");
        nieuweSpreuk(6, 0, "Gaat juni goed voorbij, dan is men in juli nog blij.");
        nieuweSpreuk(6, 0, "Hoort ge in juni de donder kraken, dan maken de boeren goede zaken.");
        nieuweSpreuk(6, 0, "In juni dondergevaar, dan is het een vruchtbaar jaar.");
        nieuweSpreuk(6, 0, "In juni koude en een regenvlaag, ziet het boerke niet zo graag.");
        nieuweSpreuk(6, 0, "In juni te veel regen in de nok, schaadt de bij en de bonenstok.");
        nieuweSpreuk(6, 0, "In Juni veel regen, komt wijngaard en bijen ongelegen.");
        nieuweSpreuk(6, 0, "Is de zomeravond mistig, dan is het weer met gaven kwistig.");
        nieuweSpreuk(6, 0, "Is er in juni pas zonneschijn, dan wordt de zomer erg klein maar fijn.");
        nieuweSpreuk(6, 0, "Is juni nat en guur, dan wordt alles slecht en duur.");
        nieuweSpreuk(6, 0, "Juni met veel donder, brengt de oogst ten onder.");
        nieuweSpreuk(6, 0, "Juni regen geeft veel zegen, maar met een bijtje erbij, en het zonnetje er boven, doet de boer de Here loven.");
        nieuweSpreuk(6, 0, "Juniregen is God’s zegen, komt zonneschijn daarbij, dan maakt het boer en stadslui blij.");
        nieuweSpreuk(6, 0, "Juniweer meer droog dan nat, vult met goede wijn het vat.");
        nieuweSpreuk(6, 0, "Mei niet te koel en niet te nat en niet te droog, vult de schuren hoog.");
        nieuweSpreuk(6, 0, "Met een zomerwervelwind, is het weer ons goed gezind.");
        nieuweSpreuk(6, 0, "Met St. Jan de wind uit het noorden, het goede weer is geboren.");
        nieuweSpreuk(6, 0, "Niet te koel, niet te zwoel, niet te nat, en niet te droog, vult de schuren hoog.");
        nieuweSpreuk(6, 0, "Op juni komt het aan, of de oogst zal bestaan.");
        nieuweSpreuk(6, 0, "Vliegen de vleermuizen ’s avonds rond, dan komt er mooi weer in de vroege stond.");
        nieuweSpreuk(6, 0, "Wie nu zijn vel niet brandt, staat starks als een bleekscheet op het strand.");
        nieuweSpreuk(6, 0, "Zo heet het is in juni, zo koud het is in december.");
        nieuweSpreuk(6, 0, "Zware onweers baren dikke korenaren.");
        nieuweSpreuk(7, 26, "Bouwt op St.Anna (26-7) de mier grote hopen, de winter zal niet zacht verlopen.");
        nieuweSpreuk(7, 25, "St Jacob (25-7) koud en rein, koud zal de Kerst zijn.");
        nieuweSpreuk(7, 25, "St Jacob (25-7) met zonneschijn, voorspeld de winter fijn.");
        nieuweSpreuk(7, 22, "Regen op St.Magdaleen (22-7), dan regent het dagen achter een.");
        nieuweSpreuk(7, 20, "Regen met Sint Margriet (20-7) geeft zes weken boerenverdriet.");
        nieuweSpreuk(7, 13, "Wanneer het op St. Henricus (13-7) droog is of regent, zeven weken duurt die zegen.");
        nieuweSpreuk(7, 10, "Regent het op 7 Broedersdag (10-7), dan kan men zeven weken regen verwachten.");
        nieuweSpreuk(7, 6, "Als het op St. Godelieve (6-7) regent, vult zij haar putje 40 dagen met regen.");
        nieuweSpreuk(7, 2, "Komt Maria (2-7) in de regen nicht Elisabeth tegen, duurt het zes weken gewis, voort het weer schoon is.");
        nieuweSpreuk(7, 0, "Als de schaapjes onrustig aan de hemel staan kan men niet zonder paraplu uit wandelen gaan.");
        nieuweSpreuk(7, 0, "Brengt juli hete gloed, zo gedijt september goed.");
        nieuweSpreuk(7, 0, "De wakkere hooimaand geeft de zeisen, de maaier in de hand met vlijt, daar lege schuren hooi vereisen, om het vee te voeden in wintertijd.");
        nieuweSpreuk(7, 0, "In juli ’s nachts regen en overdag veel zon, vult in augustus menig schuur, zak en ton.");
        nieuweSpreuk(7, 0, "Is de eerste juli regenachtig, gans de maand is twijfelachtig");
        nieuweSpreuk(7, 0, "Is in juli de morgen rood, ’s avonds verkeert het weer in nood.");
        nieuweSpreuk(7, 0, "Is juli heet en droog, dan houdt de winter een kwaad betoog.");
        nieuweSpreuk(7, 0, "Juli helder en klaar,heet altijd een goed jaar.");
        nieuweSpreuk(7, 0, "Juli zonnebrand wenst de man op ’t land.");
        nieuweSpreuk(7, 0, "Met St.Magriet droog, dan 6 weken de zon in het oog.");
        nieuweSpreuk(7, 0, "Morgenregen en vroege gasten blijven zelden overnachten.");
        nieuweSpreuk(7, 0, "Prijkt juli in hete gloed, dan zijn in de herfst de vruchten goed.");
        nieuweSpreuk(7, 0, "Slechts in juli-gloed wordt de vrucht en wijn eerst goed.");
        nieuweSpreuk(7, 0, "Wanneer de oostenwind tegen den avond gaat liggen, waait hij ligt de volgende dag opnieuw.");
        nieuweSpreuk(7, 0, "Wisselen in juli regen en zonneschijn, het zal het naaste jaar voor de boeren kermis zijn.");
        nieuweSpreuk(7, 0, "Zonder dauw geen regen, heet het in juli allerwegen.");
        nieuweSpreuk(8, 24, "Is het weer op St.Barthel (24-8) warm en schoon, dan draagt de herfst een gouden kroon.");
        nieuweSpreuk(8, 15, "Is het weer op Maria Hemelvaart (15-8) mooi, zo zal de herfst van het zelfde wezen.");
        nieuweSpreuk(8, 13, "Het weer St. Casiaan (13-8), houdt nog dagen aan.");
        nieuweSpreuk(8, 10, "Op St.Laurens (10-8) een regenvlaag, 6 weken duurt de regenplaag.");
        nieuweSpreuk(8, 4, "Is het heet op St.Domijn (4-8), het zal een strenge winter zijn.");
        nieuweSpreuk(8, 0, "Als augustus zonder regen heen zou gaan dan zullen de koeien straks mager in de stal staan.");
        nieuweSpreuk(8, 0, "Als de ooievaars na de 21e nog blijven, zal een zachte winter binnendrijven.");
        nieuweSpreuk(8, 0, "Als er ‘s-avonds muggenzwermen dansen krijgt mooi weer nieuwe kansen.");
        nieuweSpreuk(8, 0, "Als voor ’t laatst de koekoek roept, dan bederven de noten.");
        nieuweSpreuk(8, 0, "Begin augustus met regenvlagen, in de laatste dagen zal de regen ons weer plagen.");
        nieuweSpreuk(8, 0, "Blijven de zwaluwen nog lang zwieren zal de winter ons humeur niet verstieren.");
        nieuweSpreuk(8, 0, "Blijven de zwaluwen ook nog na de 25 ste, wees voor de winter niet bang.");
        nieuweSpreuk(8, 0, "Geeft begin augustus veel zonneschijn dan zal het een strenge winter zijn.");
        nieuweSpreuk(8, 0, "Is de eerste week in augustus heet, zorg voor goed warm winterkleed.");
        nieuweSpreuk(8, 0, "Menigeen heeft het al ondervonden, wervelwinden zijn aan augustus verbonden.");
        nieuweSpreuk(8, 0, "Noorderwind in augustus brengt bestendig weer.");
        nieuweSpreuk(8, 0, "Regenboog in d’avondstond, leg dan uw hoofd op een zachte grond.");
        nieuweSpreuk(8, 0, "Wanner de leeuwerik hoog in de lucht zweeft, zo brengt het ons mooi weer.");
        nieuweSpreuk(8, 0, "Zo d’eerste oogstweek is heet, een lange winter staat gereed.");
        nieuweSpreuk(9, 29, "Trekken voor St. Machiel (29-9) de vogels niet, geen winter is nog in het verschiet.");
        nieuweSpreuk(9, 29, "Vallen de eikels al voor St. Machiel (29-9), dan snijdt de winter door lijf en ziel.");
        nieuweSpreuk(9, 22, "Is het op St. Mauritius (22-9) helder, dan gaan er veel schepen naar de kelder. (er worden dan veel stormen verwacht).");
        nieuweSpreuk(9, 21, "Op Mattheus (21-9) storm en wind, bestaat de kans dat men met de komende Pasen nog de winter vindt.");
        nieuweSpreuk(9, 17, "Met Lambertus (17-9) zonneschijn, het zal een droog voorjaar zijn.");
        nieuweSpreuk(9, 16, "Op de dag van Ludmilla (16-9) een zeer vroom kind, blaast vaak een forse wind.");
        nieuweSpreuk(9, 8, "Mooi weer op Maria’s geboorte (8-9), dit weer gaat nog vier of acht weken zo voort.");
        nieuweSpreuk(9, 1, "Is het op St. Egidus (1-9) heet, het geeft een schone herfst met zweet.");
        nieuweSpreuk(9, 1, "Met St.Giel (1-9) zonneschijn, het zal dan nog 4 weken zo zijn.");
        nieuweSpreuk(9, 0, "Als de R is in de maand, is het weer niet altijd meegaand.");
        nieuweSpreuk(9, 0, "Als in september de donder knalt, zal met Kerst de sneeuw in hopen vallen.");
        nieuweSpreuk(9, 0, "Die zijn onkruid een jaar laat staan, kan zeven jaar uit wieden gaan.");
        nieuweSpreuk(9, 0, "Donder in september, sneeuw in maart.");
        nieuweSpreuk(9, 0, "Draagt de haas nog lang zijn zomerkleed dan is de winter nog niet gereed.");
        nieuweSpreuk(9, 0, "Een warme september, een droge oktober.");
        nieuweSpreuk(9, 0, "Hangen er nu veel noten aan de twijgen dan gaan we een strenge winter krijgen.");
        nieuweSpreuk(9, 0, "Is het 1 september heerlijk weer, de herfst zal mooi zijn evenzeer.");
        nieuweSpreuk(9, 0, "Is het weer in september in een goed humeur dan dragen de bladeren in oktober volop kleur.");
        nieuweSpreuk(9, 0, "Komen de pluimen aan het riet, bedenk het is nazomer en geniet.");
        nieuweSpreuk(9, 0, "Op de 5 de september wordt bewezen, wat het voor weer de hele maand zal wezen.");
        nieuweSpreuk(9, 0, "Op de 5e september wordt bewezen, wat het voor weer de hele maand zal wezen.");
        nieuweSpreuk(9, 0, "Schijnt de herfstzon met zomerkracht dat maakt veelal de wintermaand ook zacht.");
        nieuweSpreuk(9, 0, "Schijnt de herfstzon met zomerkracht, maakt veelal de winter zacht.");
        nieuweSpreuk(9, 0, "Schijnt herfstmaands zon met zomerkracht, maakt veelal wintermaand ook zacht.");
        nieuweSpreuk(9, 0, "September is altijd mooi: Het is de meimaand in herfsttooi.");
        nieuweSpreuk(9, 0, "Trekvogels in septembernacht, ze maken de kersttijd zacht.");
        nieuweSpreuk(9, 0, "Vallen de bladeren vroeg, dan wordt de herfst niet oud.");
        nieuweSpreuk(9, 0, "Vallende eikels voor Sint Michiel, snijdt de winter door lijf en ziel.");
        nieuweSpreuk(9, 0, "Vorst in september, zacht in december.");
        nieuweSpreuk(9, 0, "Warm in september, koud in december.");
        nieuweSpreuk(10, 31, "Op de laatste oktober (31-10), houdt de natuur zich sober.");
        nieuweSpreuk(10, 21, "Zoals het weer is met St. Ursela (21-10), zo zal ook de winter wezen.");
        nieuweSpreuk(10, 14, "Wordt men op Callistes (14-10) een warme wind gewaar, dan wordt de zomer een twijfelaar.");
        nieuweSpreuk(10, 11, "Treedt Gommarus (11-10) met droogte in, de zomer zal nat zijn in het begin.");
        nieuweSpreuk(10, 11, "Volgen op Gommarus (11-10) natte dagen, er volgt een zomer met veel natte dagen.");
        nieuweSpreuk(10, 9, "Regen met Sint Denijs (9-10), voorspelt een natte winter en weinig ijs.");
        nieuweSpreuk(10, 1, "Als het regent op St Bavis (1-10), dan regent het met Kerst(mis).");
        nieuweSpreuk(10, 0, "Als het waait en vriest in de oktobernacht, dan verwachten wij een januari zacht.");
        nieuweSpreuk(10, 0, "Blinkt oktober in zonnegoud de winter volgt snel en koud.");
        nieuweSpreuk(10, 0, "Brengt oktober veel vorst en wind, zo zijn januari en februari zeer mild.");
        nieuweSpreuk(10, 0, "Brengt oktober vorst en sneeuw, men hoort in de winter veel klaaggeschreeuw.");
        nieuweSpreuk(10, 0, "Het laatste weer van oktober, reikt november de hand.");
        nieuweSpreuk(10, 0, "In de wijnmaand zon, winter kent geen pardon.");
        nieuweSpreuk(10, 0, "Is de herfst het weer lang en klaar, vroeg is dan een strenge winter daar.");
        nieuweSpreuk(10, 0, "Is oktober warm en fijn, het zal een scherpe winter zijn,");
        nieuweSpreuk(10, 0, "Is oktober warm en fijn, het zal een scherpe winter zijn, maar is het nat en koel, ’t is van een zachte winter een voorgevoel!");
        nieuweSpreuk(10, 0, "Komt in oktober veel mist, dan heeft januari veel ijs in de kist.");
        nieuweSpreuk(10, 0, "maar is het nat en koel, ’t is van een zachte winter een voorgevoel! ");
        nieuweSpreuk(10, 0, "Oktober brengt ons wijn en zonnige dagen maar ook jicht en andere plagen.");
        nieuweSpreuk(10, 0, "Oktober geeft ons wijn en zonnige dagen, maar ook jicht en andere plagen.");
        nieuweSpreuk(10, 0, "Oktober met groene blaan (bladeren), duidt een strenge winter aan.");
        nieuweSpreuk(10, 0, "Oktoberweer komt terug in maart.");
        nieuweSpreuk(10, 0, "Schijnt in de wijnmaand volop de zon dan kent de winter geen pardon.");
        nieuweSpreuk(10, 0, "Volgen op Gommarus natte dagen, er volgt een zomer met veel natte dagen.");
        nieuweSpreuk(10, 0, "Warme oktober dagen, februari vlagen.");
        nieuweSpreuk(10, 0, "Worden de bladeren geel en krom, kijk naar uw kachel om.");
        nieuweSpreuk(11, 29, "IJs op de dag van Saturijn (29-11), het weer maakt daarna korte mette met dit venijn.");
        nieuweSpreuk(11, 25, "Vriest het op St. Katrien (25-11), dan vriest het nog 6 weken nadien.");
        nieuweSpreuk(11, 22, "De dag aan St. Cecilia (22-11) gewijd, is de maatstaf voor de wintertijd.");
        nieuweSpreuk(11, 19, "St. Elisabeth (19-11) doet ons verstaan, hoe de winter zal vergaan.");
        nieuweSpreuk(11, 11, "Als het nevelig is op St. Martijn (11-11), dan zal de winter niet koud zijn.");
        nieuweSpreuk(11, 11, "Is er een donkere lucht op St. Martijn (11-11), zo zal het een zachte winter zijn.");
        nieuweSpreuk(11, 11, "Is er met St. Martijn (11-11) nog loof aan de bomen, dan mag men van een strenge winter dromen.");
        nieuweSpreuk(11, 11, "Maar heeft St. Martijn (11-11) een witte baard, dan blijft ons sneeuw noch ijs gespaard.");
        nieuweSpreuk(11, 11, "Maar is de dag op St. Martijn (11-11) helder, de vorst dringt dan door tot in de kelder.");
        nieuweSpreuk(11, 10, "Een zuidenwind op de dag voor St. Martijn (10-11), dan zal het een zachte winter zijn.");
        nieuweSpreuk(11, 6, "Het weer op Leonardusdag (6-11), blijft gewoonlijk tot de Kerstdag.");
        nieuweSpreuk(11, 2, "Sneeuw op Allerzielen (2-11), voorspelt een zacht voorjaar.");
        nieuweSpreuk(11, 1, "Als het met Allerheiligen (1-11) sneeuwt, leg dan vast uw pels gereed.");
        nieuweSpreuk(11, 1, "Brengt Allerheiligen (1-11) winterweer, tien dagen duurt het zeer.");
        nieuweSpreuk(11, 1, "Houden de kraaien voor Allerheiligen (1-11) al school, zorg dan voor hout en kool.");
        nieuweSpreuk(11, 0, "Als ’t in November ’s morgens broeit, wis dat de storm ’s avonds loeit.");
        nieuweSpreuk(11, 0, "Als het nevelig is op St. Martijn, dan zal de winter niet koud zijn.");
        nieuweSpreuk(11, 0, "Als het vriest in november, dan volgt er sneeuw in december.");
        nieuweSpreuk(11, 0, "Als in november het water stijgt, gedurende de winter gij ’t nog vaker krijgt.");
        nieuweSpreuk(11, 0, "Als op St. Martijn de ganzen op het ijs staan,moeten ze met Kerst door het slijk gaan.");
        nieuweSpreuk(11, 0, "Brengt Allerheiligen winterweer, tien dagen duurt het zeer.");
        nieuweSpreuk(11, 0, "Donder in november, laat een jaar goed verlopen.");
        nieuweSpreuk(11, 0, "Houden de kraaien voor Allerheiligen al school, zorg dan voor hout en kool.");
        nieuweSpreuk(11, 0, "Is de hemel al te blauw, spoedig wordt hij dan weer grauw.");
        nieuweSpreuk(11, 0, "Is er met St. Martijn nog loof aan de bomen, dan mag men van een strenge winter dromen.");
        nieuweSpreuk(11, 0, "Maakt de spin in ’t web een scheur, dan klopt weldra de stormwind aan de deur.");
        nieuweSpreuk(11, 0, "Maar heeft St. Martijn een witte baard, dan blijft ons sneeuw nog ijs gespaard.");
        nieuweSpreuk(11, 0, "Maar is de dag op St. Martijn helder, de vorst dringt dan door tot in de kelder.");
        nieuweSpreuk(11, 0, "Met Allerheiligen vochtig weer, sneeuwbuien volgen keer op keer.");
        nieuweSpreuk(11, 0, "Na helder weer nu sombere mist, heeft zeker ook nog vorst in de kist.");
        nieuweSpreuk(11, 0, "November heeft maar 30 dagen, maar dubbel wind en regenvlagen.");
        nieuweSpreuk(11, 0, "November heeft maar dertig dagen, maar dubbel wind en regenvlagen.");
        nieuweSpreuk(11, 0, "November met zijn regenvlagen, brengt verkoudheid, jicht en andere plagen");
        nieuweSpreuk(11, 0, "November warm en fijn, het zal een strenge winter zijn.");
        nieuweSpreuk(11, 0, "Rijp aan boom en plant, houdt geen drie dagen stand.");
        nieuweSpreuk(11, 0, "Volgt de eerste sneeuw opregen, dat houdt een harde winter tegen.");
        nieuweSpreuk(11, 0, "Wintert het op St. Klemens fel, dan wordt de lente klaar en fel.");
        nieuweSpreuk(11, 0, "Zwaait de winter in november al met zijn staf, zijn rijk is van korte duur voor straf.");
        nieuweSpreuk(12, 21, "Als met St. Thomas (21-12) de dagen gaan lengen, beginnen de nachten te strengen.");
        nieuweSpreuk(12, 7, "St. Ambroos (7-12), patroon van de bijen, en de spreewen, houdt van waaien en van sneeuwen.");
        nieuweSpreuk(12, 6, "Brengt St. Nicolaas (6-12) ijs, dan brengt de Kerstman regen.");
        nieuweSpreuk(12, 4, "St. Barbara (4-12) gaat graag in een wit kleed naar het bal.");
        nieuweSpreuk(12, 1, "Brengt St. Eligius (1-12), de eerste dooi?, begint het echter op die dag te vriezen, dan krijgen we vier weken vorst voor de kiezen.");
        nieuweSpreuk(12, 0, "Als ’t regent in de winter, is het goed planten in de zomer.");
        nieuweSpreuk(12, 0, "Als met Kertsmis de muggen zwermen, kunt ge met Pasen uw oren wermen (warmen)");
        nieuweSpreuk(12, 0, "Als met Sint Thomas de dagen lengen, beginnen de nachten te strengen.");
        nieuweSpreuk(12, 0, "Blaast de noorderwind met een decembermaan, dan houdt de winter vier maan den aan.");
        nieuweSpreuk(12, 0, "December veranderlijk en zacht, is een winter is een winter zonder kracht.");
        nieuweSpreuk(12, 0, "December veranderlijk en zacht, is een winter zonder kracht.");
        nieuweSpreuk(12, 0, "December vol met mist, goud in de kist.");
        nieuweSpreuk(12, 0, "December zacht en dikwijls regen, geeft weinig hoop op rijke zegen.");
        nieuweSpreuk(12, 0, "Decemberregen is geen zegen.");
        nieuweSpreuk(12, 0, "Donder in de decembermaand, belooft veel wind in ’t jaar aanstaand.");
        nieuweSpreuk(12, 0, "Met de decembermaand is het jaar weer uit, gelukkig wiens balans goed sluit.");
        nieuweSpreuk(12, 0, "Op een droge december, volgt een droog voorjaar, en een droge zomer.");
        nieuweSpreuk(12, 0, "Plenst in de winter veel regen neer, dan krijgen we mooi zomerweer.");
        nieuweSpreuk(12, 0, "Sneeuw veel en lang, maakt de klaver niet bang.");
        nieuweSpreuk(12, 0, "Veel sneeuw op Oudjaar, veel hooi in ’t nieuwe jaar.");
        nieuweSpreuk(12, 0, "Zijn er in december veel mollen, dan laat de winter met zich sollen.");
    }
}
